### # 파이썬 사이킷런으로 나이브 베이즈 분류기 문제 풀어보기!
    - 문일철 교수님 기계학습 CH3.의 퀴즈

In [3]:
import pandas as pd
import numpy as np

In [222]:
# 주어진 데이터
df = pd.DataFrame({'Sky':['Sunny','Sunny', 'Rainy', 'Sunny'],
                   'Temp':['Warm','Warm','Cold','Warm'],
                 'Humid':['Normal', 'High', 'High', 'High'],
                 'Wind':['Strong','Strong', 'Strong', 'Strong'],
                 'Water':['Warm', 'Warm', 'Warm', 'Cool'],
                 'Forecst':['Same','Same','Change','Change'],
                 'EnjoySpt':['Y','Y', 'N', 'Y']})
df

     Sky  Temp   Humid    Wind Water Forecst EnjoySpt
0  Sunny  Warm  Normal  Strong  Warm    Same        Y
1  Sunny  Warm    High  Strong  Warm    Same        Y
2  Rainy  Cold    High  Strong  Warm  Change        N
3  Sunny  Warm    High  Strong  Cool  Change        Y

In [223]:
# 변수값을 수치화한다.
# Import LabelEncoder (string -> int)
from sklearn import preprocessing

#creating labelEncoder
le = preprocessing.LabelEncoder()

# (string -> int)
print('인코딩할 컬럼들: ', df.columns)
for col in df.columns.tolist():
    print(col)
    name = f'{col}_encoded'
    df[name] = le.fit_transform(df[col].values)

인코딩할 컬럼들:  Index(['Sky', 'Temp', 'Humid', 'Wind', 'Water', 'Forecst', 'EnjoySpt'], dtype='object')
Sky
Temp
Humid
Wind
Water
Forecst
EnjoySpt

In [224]:
display(df)
print(df.columns)
# training 에 사용할 칼럼들
x_columns = ['Sky_encoded', 'Temp_encoded', 'Humid_encoded', 'Wind_encoded','Water_encoded', 'Forecst_encoded']

,Sky,Temp,Humid,Wind,Water,Forecst,EnjoySpt,Sky_encoded,Temp_encoded,Humid_encoded,Wind_encoded,Water_encoded,Forecst_encoded,EnjoySpt_encoded
0,Sunny,Warm,Normal,Strong,Warm,Same,Y,1,1,1,0,1,1,1
1,Sunny,Warm,High,Strong,Warm,Same,Y,1,1,0,0,1,1,1
2,Rainy,Cold,High,Strong,Warm,Change,N,0,0,0,0,1,0,0
3,Sunny,Warm,High,Strong,Cool,Change,Y,1,1,0,0,0,0,1

Index(['Sky', 'Temp', 'Humid', 'Wind', 'Water', 'Forecst', 'EnjoySpt',
       'Sky_encoded', 'Temp_encoded', 'Humid_encoded', 'Wind_encoded',
       'Water_encoded', 'Forecst_encoded', 'EnjoySpt_encoded'],
      dtype='object')

In [185]:
df[x_columns].values

array([[1, 1, 1, 0, 1, 1],
       [1, 1, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 0],
       [1, 1, 0, 0, 0, 0]])

In [186]:
df['EnjoySpt_encoded'].values

array([1, 1, 0, 1])

### #사이킷런에서 제공하는 나이브베이즈 모형
    사이킷런의 naive_bayes 서브패키지에서는 다음과 같은 세가지 나이브베이즈 모형 클래스를 제공한다.

- GaussianNB: 정규분포 나이브베이즈
- BernoulliNB: 베르누이분포 나이브베이즈
- MultinomialNB: 다항분포 나이브베이즈

In [214]:
# 모형 3개를 하나씩 적용하여 그 결과를 비교해보자!
# training and test 과정
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Split dataset into training set and test set
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(df[x_columns].values, df['EnjoySpt_encoded'].values, test_size=0.3, random_state=109)

#Create a Classifier
#clf = GaussianNB()  # 가우시안 분포 나이브 베이즈
#clf = BernoulliNB() # 베르누이 분포 나이브 베이즈
clf = MultinomialNB() # 다항분포 나이브 베이즈

# Train the model using the training sets
clf.fit(X_train, y_train)
# predict test set
y_pred = clf.predict(X_test)
# Model Accuracy, how often is the classifier correct? 분류기 정확도 측정
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

Accuracy: 1.0

### # 예측할 데이터 만들기

In [215]:
# 실제 예측할 데이터의 변수 : {'Sky':'Sunny', 'Temp':'Warm', 'Humid':'High', 'Wind':'strong', 'Water':'Warm', 'Forecst':'Change'}
# 제대로 된 라벨인코딩을 위해 더미를 넣어줌
new = pd.DataFrame({'Sky':['Sunny', 'Rainy', 'Sunny', 'Rainy'],
                        'Temp':['Warm', 'Cold', 'Warm', 'Cold'],
                         'Humid':['High', 'Normal', 'High', 'High'],
                        'Wind':['Strong', 'Strong', 'Strong', 'Strong'],
                        'Water':['Warm', 'Cool', 'Cool', 'Warm'],
                        'Forecst':['Change', 'Same', 'Change', 'Change']})

# 라벨인코딩...
for col in new.columns.tolist():
    print(col)
    name = f'{col}_encoded'
    new[name] = le.fit_transform(new[col].values)
    
display(new)

Sky
Temp
Humid
Wind
Water
Forecst

,Sky,Temp,Humid,Wind,Water,Forecst,Sky_encoded,Temp_encoded,Humid_encoded,Wind_encoded,Water_encoded,Forecst_encoded
0,Sunny,Warm,High,Strong,Warm,Change,1,1,0,0,1,0
1,Rainy,Cold,Normal,Strong,Cool,Same,0,0,1,0,0,1
2,Sunny,Warm,High,Strong,Cool,Change,1,1,0,0,0,0
3,Rainy,Cold,High,Strong,Warm,Change,0,0,0,0,1,0

### # 분류기 이용 -> prediction

In [225]:
# 학습된 모델분류기로 새로 들어온 데이터의 Y값을 prediction한다
new['label_pred'] = clf.predict(new[x_columns].values)
# prediction의 확률도 계산해준다.
y_pred_proba = clf.predict_proba(new[x_columns].values)
print(y_pred)
print(y_pred_proba)
# pred 0일 확률
new['Prob[0]'] = y_pred_proba[:,0]
# pred 1일 확률
new['Prob[1]'] = y_pred_proba[:,1]

[1 1]
[[0.42158516 0.57841484]
 [0.50505051 0.49494949]
 [0.33783784 0.66216216]
 [0.58823529 0.41176471]]

In [191]:
# 가우시안을 썼을 때,
GNB = new.copy()

In [195]:
# 베르누이를 썼을 때,
BNB = new.copy()

In [217]:
# 다항분포를 썼을 때,
MNB = new.copy()

In [231]:
print('가우시안 분포')
display(GNB)
print('\n\n=============================================================')
print('\n\n베르누이 분포')
display(BNB)
print('\n\n=============================================================')
print('\n\n다항 분포')
display(MNB)

가우시안 분포

,Sky,Temp,Humid,Wind,Water,Forecst,Sky_encoded,Temp_encoded,Humid_encoded,Wind_encoded,Water_encoded,Forecst_encoded,label_pred,Prob[0],Prob[1]
0,Sunny,Warm,High,Strong,Warm,Change,1,1,0,0,1,0,1,0.0,1.0
1,Rainy,Cold,Normal,Strong,Cool,Same,0,0,1,0,0,1,0,1.0,0.0
2,Sunny,Warm,High,Strong,Cool,Change,1,1,0,0,0,0,1,0.0,1.0
3,Rainy,Cold,High,Strong,Warm,Change,0,0,0,0,1,0,0,1.0,0.0

=============================================================


베르누이 분포

,Sky,Temp,Humid,Wind,Water,Forecst,Sky_encoded,Temp_encoded,Humid_encoded,Wind_encoded,Water_encoded,Forecst_encoded,label_pred,Prob[0],Prob[1]
0,Sunny,Warm,High,Strong,Warm,Change,1,1,0,0,1,0,1,0.333333,0.666667
1,Rainy,Cold,Normal,Strong,Cool,Same,0,0,1,0,0,1,0,0.666667,0.333333
2,Sunny,Warm,High,Strong,Cool,Change,1,1,0,0,0,0,1,0.333333,0.666667
3,Rainy,Cold,High,Strong,Warm,Change,0,0,0,0,1,0,0,0.888889,0.111111

=============================================================


다항 분포

,Sky,Temp,Humid,Wind,Water,Forecst,Sky_encoded,Temp_encoded,Humid_encoded,Wind_encoded,Water_encoded,Forecst_encoded,label_pred,Prob[0],Prob[1]
0,Sunny,Warm,High,Strong,Warm,Change,1,1,0,0,1,0,1,0.421585,0.578415
1,Rainy,Cold,Normal,Strong,Cool,Same,0,0,1,0,0,1,0,0.505051,0.494949
2,Sunny,Warm,High,Strong,Cool,Change,1,1,0,0,0,0,1,0.337838,0.662162
3,Rainy,Cold,High,Strong,Warm,Change,0,0,0,0,1,0,0,0.588235,0.411765

### # prediction 결과는 같으나, pred_proba가 가우시안NB > 베르누이NB > 다항분포NB 순으로 점점 낮아지게 된다. 
    - Q. 데이터의 형태에 따라 선택해야하는 나이브 베이즈 모형이 달라지는가?
    - 설명을 찾아봐도 확실한 이해가 되지 않음 ㅜㅜ
    - 설명 링크 1: https://datascienceschool.net/view-notebook/c19b48e3c7b048668f2bb0a113bd25f7/
    - 설명 링크 2: https://books.google.co.kr/books?id=tPaTDwAAQBAJ&pg=PA99&lpg=PA99&dq=%EC%82%AC%EC%9D%B4%ED%82%B7%EB%9F%B0+BernoulliNB&source=bl&ots=1Y0EYOZS4W&sig=ACfU3U1HRgCQMU2mSYtfEB77zX-fQtXmnw&hl=ko&sa=X&ved=2ahUKEwjlo_eRvtLnAhVmxYsBHRpCCokQ6AEwAnoECAkQAQ#v=onepage&q=%EC%82%AC%EC%9D%B4%ED%82%B7%EB%9F%B0%20BernoulliNB&f=false